Clean up check-qt-js task and use python+node image

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -78,22 +78,41 @@ jobs:
 
   check-qt-js:
     docker:
-      - image: circleci/python:latest
+      - image: cimg/python:3.9.4-node
     steps:
       - checkout
       - run:
           name: Install Javascript dependencies and build Glean.js for Qt
           command: |
-            # We are on the CircleCI python docker image, so let's install npm and node.
-            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.0/install.sh | bash
-            export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
-            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
-            nvm install node
             npm --prefix ./glean install
             npm --prefix ./glean run build:qt
       - run:
-          name: Verify no Javascript errors found in Qt
-          command: bin/qt-js-check.sh
+          name: Setup Python environment
+          command: |
+            cd samples/qt-qml-app
+            python3 -m venv venv
+            source venv/bin/activate
+            pip install -r requirements.txt
+            glean_parser translate metrics.yaml pings.yaml -f javascript -o generated
+      - run:
+          name: Setup Qt dependency
+          command: |
+            # Setting this gives us enhanced output on plugin errors.
+            export QT_DEBUG_PLUGINS=1
+            sudo apt-get install xvfb
+            sudo apt-get install libxcb-icccm4 libxcb-image0 libdbus-1-3 libxcb-xfixes0 libxkbcommon-x11-0 libxcb-xkb1 libxcb-xinerama0 libxcb-keysyms1 libxcb-randr0 libxcb-shape0 libxrender1 libxcb-render-util0
+            xvfb-run python main.py &> qml.log &
+      - run:
+          name: Run the Qt sample app and check for errors
+          command: |
+            xvfb-run python main.py &> qml.log &
+            # Wait for app to start
+            sleep 10
+            if ! grep -q "Initialized Glean succesfully." "qml.log"; then
+              echo "\n\n\033[1;91m** Failed to initialize Glean in Qt! See more logs below. **\033[0m\n\n"
+              cat qml.log
+              exit 1
+            fi
 
   publish:
     docker:
